version: 2.1

aliases:
  - &android_environment
    docker:
      - image: cimg/android:2024.01
    resource_class: large

jobs:
  run-unit-test:
    macos:
      xcode: 15.4
    steps:
      - checkout
      - run:
          name: Run iOS Tests
          command: ./gradlew :analytics:iosSimulatorArm64Test
      - run:
          name: Run Android Tests
          command: ./gradlew :analytics:testDebugUnitTest


workflows:
  main:
    jobs:
      - "run-unit-test"