version: 2.1

aliases:
  - &android_environment
    docker:
      - image: cimg/android:2024.01
    resource_class: large

jobs:
  run-unit-test:
    <<: *android_environment
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ./gradlew :analytics:allTests

workflows:
  main:
    jobs:
      - "run-unit-test"